server:
  port: 8090

cron:
  startSendBrukerBeskjed: 0 15 14 * * *

management:
  endpoint:
    health:
      show-details: always
  endpoints.web:
      exposure:
        include: info, health, metrics, prometheus
      base-path: "/internal"
  metrics:
    export:
      prometheus:
        enabled: true
    web:
      server:
        request:
          autotime:
            enabled: true
