apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: soknadsmottaker
  namespace: q0
  labels:
    team: team-soknad
spec:
  image: {{image}}
  port: 8090
  liveness:
    path: /internal/isAlive
    initialDelay: 20
    failureThreshold: 10
    timeout: 1
  readiness:
    path: /internal/isReady
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: true
    path: /internal/prometheus
  replicas:
    min: 2
    max: 4
  resources:
    limits:
      cpu: 3000m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  ingresses:
    - "https://soknadsmottaker-q0.dev.adeo.no"
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/serviceuser
        kvPath: /serviceuser/data/dev/srvsoknadsmottaker
      - mountPath: /var/run/secrets/nais.io/kv
        kvPath: /kv/preprod/fss/soknadsmottaker/default
      - mountPath: /var/run/secrets/nais.io/appdynamics
        kvPath: /apikey/appdynamics/dev

  env:
    - name: APP_VERSION
      value: {{ app_version }}
    - name: KAFKA_BOOTSTRAP_SERVERS
      value: b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443,b27apvl00047.preprod.local:8443
    - name: SCHEMA_REGISTRY_URL
      value: https://kafka-schema-registry.nais.preprod.local
    - name: KAFKA_SECURITY
      value: 'TRUE'
    - name: KAFKA_SECPROT
      value: SASL_SSL
    - name: KAFKA_SASLMEC
      value: PLAIN
    - name: APPLICATION_PROFILE
      value: dev
    - name: KAFKA_TOPIC
      value: privat-soknadInnsendt-v1-q0
