server:
  port: 8090

management:
  endpoint:
    health:
      show-details: always
  endpoints.web:
    exposure:
      include: info, health, metrics, prometheus, save
    base-path: "/"
    path-mapping:
      info: "/internal/isAlive"
  metrics:
    export:
      prometheus:
        enabled: true
