server:
  port: 8090

management:
  endpoint:
    health:
      show-details: always
  endpoints.web:
    exposure:
      include: "*"
    path-mapping:
      info: "/internal/isAlive"
      save: "/save"
  metrics:
    export:
      prometheus:
        enabled: true
