server:
  port: 8090

management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: ["info", "health", "prometheus", "metrics"]

srvsoknadsmottaker: [username: srvsoknadsmottaker, password: test]

application:
  kafka:
    bootstrap-servers: localhost:9092

---

spring:
  profiles: docker

application:
  kafka:
    bootstrap-servers: kafka-broker:29092
