server:
  port: 8090

management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: ["info", "health", "prometheus", "metrics"]

application:
  kafka:
    bootstrap-servers: localhost:9092

---

spring:
  profiles: docker

KAFKA_BOOTSTRAP_SERVERS: kafka-broker:9092
application:
  kafka:
    bootstrap-servers: kafka-broker:29092
