server:
  port: 8090

management:
  endpoint.health.show-details: always
  endpoints.web:
    exposure.include: info, health, metrics, prometheus, httptrace
    base-path: "/internal"
  metrics.export.prometheus.enabled: true
  health:
    db:
      enabled: true
  metrics:
    web:
      server:
        request:
          autotime:
            enabled: true
